name: Docker build
on:
  push:
    branches:
      - main
jobs:

  build:
    name:  docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code and all tags and branches
        uses: actions/checkout@v2
        id: version
        with:
          fetch-depth: 0

      - name: Get docker tag
        run: |
          tag=$(git log -1 --format=%h) 
          printf '#!/usr/bin/env python\n__version__ = \"%s\"\n' ${tag} > ./src/app/__init__.py
          echo "Setting TAG=${tag}"
          echo "TAG=${tag}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push mbari/fastapi-tator to Docker Hub
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            mbari/fastapi-tator:${{ env.TAG }}
            mbari/fastapi-tator:latest
          labels: |
            IMAGE_URI=mbari/fastapi-tator:${{ env.TAG }}